stages:
  - test
  - publish

test-job-unit:
  stage: test
  image: rust:1.58
  script:
    - cargo test --all-targets

test-job-lint:
  stage: test
  image: rust:1.58
  script:
    - rustup component add clippy
    - cargo clippy --all-targets

publish-job-crates:
  stage: publish
  rules:
    - if: $CI_PROJECT_NAMESPACE == "goodrouter" && $CI_COMMIT_TAG =~ /^v/
  image: rust:1.58
  script:
    - sed --in-place 's/^version\s*=.*$/version = "'${CI_COMMIT_TAG:1}'"/' Cargo.toml
    - cargo publish
