[package]
name = "goodrouter"
version = "0.0.0-local"
edition = "2018"
description = "a bi directional trie router for all your routing needs"
license = "ISC"
author = "LuvDaSun Software B.V."

[dependencies]
regex = "1"
itertools = "0.10"
