on:
  release:
    types:
      - published
    tags:        
      - v*

jobs:

  publish-crates:
    runs-on: ubuntu-latest
    container: rust:1.64-alpine3.15
    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: apk add tar
      - uses: actions/cache@v3
        with:
          key: ${{ github.job }}-${{ hashFiles('Cargo.lock') }}
          path: |
            .cargo/
            target/
      - run: apk add cargo-edit
      - run: cargo set-version ${GITHUB_REF_NAME:1}
      - run: cargo publish --allow-dirty
